version: "3.9"

services:
  mcq-video:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mcq-video-app
    ports:
      # Maps the public port from .env to the internal Flask port
      - "${PUBLIC_PORT:-5000}:${FLASK_RUN_PORT:-10000}"
    env_file:
      - .env
    environment:
      - DOCKER_CONTAINER=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_RUN_PORT:-10000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: mount logs directory for debugging
      - ./logs:/app/logs
    networks:
      - mcq-network

networks:
  mcq-network:
    driver: bridge